# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.cache/wt [current_project]
set_property parent.project_path C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/Full-Adder.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/AdderStage30.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/AdderStage29.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/AdderStage28.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/AdderStage27.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/AdderStage26.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/AdderStage25.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/AdderStage24.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/AdderStage23.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/AdderStage22.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/AdderStage21.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/AdderStage20.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/AdderStage19.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/AdderStage18.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/AdderStage17.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/AdderStage16.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/AdderStage15.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/AdderStage14.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/AdderStage13.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/AdderStage12.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/AdderStage11.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/AdderStage9.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/AdderStage8.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/AdderStage7.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/AdderStage6.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/AdderStage5.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/AdderStage4.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/AdderStage3.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/AdderStage2.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/AdderStage10.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/AdderStage1.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/AdderStage0.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/PartialProductRow29.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/PartialProductRow27.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/PartialProductRow25.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/PartialProductRow23.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/PartialProductRow21.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/PartialProductRow3.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/PartialProductRow5.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/PartialProductRow7.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/PartialProductRow9.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/PartialProductRow17.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/PartialProductRow19.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/PartialProductRow1.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/PartialProductRow11.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/PartialProductRow13.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/PartialProductRow15.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/PartialProductRow30.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/PartialProductRow28.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/PartialProductRow26.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/PartialProductRow20.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/PartialProductRow24.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/PartialProductRow22.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/FinalSum.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/PartialProductRow4.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/PartialProductRow6.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/PartialProductRow8.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/PartialProductRow16.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/PartialProductRow18.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/PartialProductRow0.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/PartialProductRow2.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/PartialProductRow10.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/PartialProductRow12.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/PartialProductRow14.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/PartialProductRow31.v
  C:/Users/chris/Desktop/32BitDadda/32bitdadda/32bitdadda.srcs/sources_1/new/DaddaMultiplier.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top DaddaMultiplier -part xc7a100tcsg324-1


write_checkpoint -force -noxdef DaddaMultiplier.dcp

catch { report_utilization -file DaddaMultiplier_utilization_synth.rpt -pb DaddaMultiplier_utilization_synth.pb }
